### ISSUE TITLE
Failed at the node-hid@0.3.2 install script 'sh install.sh'.

### ISSUE THREAD

**Issue by kucukkanat** [emilyrose/hidstream#4]
script 'sh install.sh'. Fails while installing from npm

**Comment by watsoncj** [comment]
Is there an error message with the failure?

**Comment by kucukkanat** [comment]
Yes.
I think form here it is enough : 

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/HID/src/HID.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "install"
gyp ERR! cwd /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/hidstream/node_modules/node-hid
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "hidstream"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! node-hid@0.3.2 install: `sh install.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-hid@0.3.2 install script 'sh install.sh'.
npm ERR! This is most likely a problem with the node-hid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     sh install.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-hid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eeksnider/Desktop/hobby/trojanv2/npm-debug.log

I have searched through the issues opened before and it seems to be a problem with nodejs v12 ? Can it be?

**Comment by watsoncj** [comment]
Is there anything else in ` /Users/eeksnider/Desktop/hobby/trojanv2/npm-debug.log` that would indicate why the make failed?

I've personally only used this library on OSX with Node.js 10.

**Comment by kucukkanat** [comment]
There seems to be a problem with sh install.sh

Here is the full debug log. Check especially 97 Error:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'node-hid' ]
2 info using npm@2.9.1
3 info using node@v0.12.3
4 verbose install initial load of /Users/eeksnider/Desktop/hobby/trojanv2/package.json
5 warn package.json trojanv2@1.0.0 No description
6 warn package.json trojanv2@1.0.0 No repository field.
7 warn package.json trojanv2@1.0.0 No README data
8 verbose installManyTop reading scoped package data from /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/express/package.json
9 verbose installManyTop reading scoped package data from /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/localtunnel/package.json
10 verbose installManyTop reading scoped package data from /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/osenv/package.json
11 verbose installManyTop reading scoped package data from /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/pushbullet/package.json
12 verbose readDependencies loading dependencies from /Users/eeksnider/Desktop/hobby/trojanv2/package.json
13 silly cache add args [ 'node-hid', null ]
14 verbose cache add spec node-hid
15 silly cache add parsed spec { raw: 'node-hid',
15 silly cache add   scope: null,
15 silly cache add   name: 'node-hid',
15 silly cache add   rawSpec: '',
15 silly cache add   spec: '*',
15 silly cache add   type: 'range' }
16 silly addNamed node-hid@*
17 verbose addNamed "*" is a valid semver range for node-hid
18 silly addNameRange { name: 'node-hid', range: '*', hasData: false }
19 silly mapToRegistry name node-hid
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/node-hid
23 verbose addNameRange registry:https://registry.npmjs.org/node-hid not in flight; fetching
24 verbose request uri https://registry.npmjs.org/node-hid
25 verbose request no auth needed
26 info attempt registry request try #1 at 2:38:35 AM
27 verbose request id 3d3a5e3804f51f74
28 verbose etag "DN6O1NZHJ5TMLPCM698WL3RQQ"
29 http request GET https://registry.npmjs.org/node-hid
30 http 304 https://registry.npmjs.org/node-hid
31 silly get cb [ 304,
31 silly get   { date: 'Fri, 22 May 2015 23:38:54 GMT',
31 silly get     via: '1.1 varnish',
31 silly get     'cache-control': 'max-age=60',
31 silly get     etag: '"DN6O1NZHJ5TMLPCM698WL3RQQ"',
31 silly get     age: '0',
31 silly get     connection: 'keep-alive',
31 silly get     'x-served-by': 'cache-ams4149-AMS',
31 silly get     'x-cache': 'MISS',
31 silly get     'x-cache-hits': '0',
31 silly get     'x-timer': 'S1432337934.406674,VS0,VE382',
31 silly get     vary: 'Accept' } ]
32 verbose etag https://registry.npmjs.org/node-hid from cache
33 verbose get saving node-hid to /Users/eeksnider/.npm/registry.npmjs.org/node-hid/.cache.json
34 silly addNameRange number 2 { name: 'node-hid', range: '*', hasData: true }
35 silly addNameRange versions [ 'node-hid',
35 silly addNameRange   [ '0.0.13',
35 silly addNameRange     '0.0.14',
35 silly addNameRange     '0.0.15',
35 silly addNameRange     '0.1.0',
35 silly addNameRange     '0.1.1',
35 silly addNameRange     '0.2.0',
35 silly addNameRange     '0.2.1',
35 silly addNameRange     '0.2.2',
35 silly addNameRange     '0.2.3',
35 silly addNameRange     '0.3.1',
35 silly addNameRange     '0.3.2' ] ]
36 silly addNamed node-hid@0.3.2
37 verbose addNamed "0.3.2" is a plain semver version for node-hid
38 silly cache afterAdd node-hid@0.3.2
39 verbose afterAdd /Users/eeksnider/.npm/node-hid/0.3.2/package/package.json not in flight; writing
40 verbose afterAdd /Users/eeksnider/.npm/node-hid/0.3.2/package/package.json written
41 silly install resolved [ { name: 'node-hid',
41 silly install resolved     description: 'USB HID device access library',
41 silly install resolved     version: '0.3.2',
41 silly install resolved     author:
41 silly install resolved      { name: 'Hans Hübner',
41 silly install resolved        email: 'hans.huebner@gmail.com',
41 silly install resolved        url: 'https://github.com/hanshuebner' },
41 silly install resolved     contributors: [ [Object] ],
41 silly install resolved     repository:
41 silly install resolved      { type: 'git',
41 silly install resolved        url: 'git://github.com/hanshuebner/node-hid.git' },
41 silly install resolved     scripts:
41 silly install resolved      { preupdate: 'sh get-hidapi.sh',
41 silly install resolved        preinstall: 'sh get-hidapi.sh',
41 silly install resolved        install: 'sh install.sh' },
41 silly install resolved     main: './index.js',
41 silly install resolved     engines: { node: '>=0.8.0' },
41 silly install resolved     license: 'MIT/X11',
41 silly install resolved     dependencies: {},
41 silly install resolved     devDependencies: {},
41 silly install resolved     gitHead: 'd9833cef3a4eff6110be3e1de5d8b5c8bb106500',
41 silly install resolved     bugs: { url: 'https://github.com/hanshuebner/node-hid/issues' },
41 silly install resolved     homepage: 'https://github.com/hanshuebner/node-hid',
41 silly install resolved     _id: 'node-hid@0.3.2',
41 silly install resolved     _shasum: '2414824b459313d1ca627fabdb4cb7a2506c0478',
41 silly install resolved     _from: 'node-hid@*',
41 silly install resolved     _npmVersion: '1.4.21',
41 silly install resolved     _npmUser: { name: 'hans', email: 'hans.huebner@gmail.com' },
41 silly install resolved     maintainers: [ [Object], [Object], [Object] ],
41 silly install resolved     dist:
41 silly install resolved      { shasum: '2414824b459313d1ca627fabdb4cb7a2506c0478',
41 silly install resolved        tarball: 'http://registry.npmjs.org/node-hid/-/node-hid-0.3.2.tgz' },
41 silly install resolved     directories: {},
41 silly install resolved     _resolved: 'https://registry.npmjs.org/node-hid/-/node-hid-0.3.2.tgz',
41 silly install resolved     readme: 'ERROR: No README data found!' } ]
42 info install node-hid@0.3.2 into /Users/eeksnider/Desktop/hobby/trojanv2
43 info installOne node-hid@0.3.2
44 verbose installOne of node-hid to /Users/eeksnider/Desktop/hobby/trojanv2 not in flight; installing
45 verbose lock using /Users/eeksnider/.npm/_locks/node-hid-508b441f17e83de6.lock for /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid
46 silly install write writing node-hid 0.3.2 to /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid
47 verbose unbuild node_modules/node-hid
48 silly gentlyRm /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid is being purged from base /Users/eeksnider/Desktop/hobby/trojanv2
49 verbose gentlyRm don't care about contents; nuking /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid
50 verbose tar unpack /Users/eeksnider/.npm/node-hid/0.3.2/package.tgz
51 verbose tar unpacking to /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid
52 silly gentlyRm /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid is being purged
53 verbose gentlyRm don't care about contents; nuking /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid
54 silly gunzTarPerm modes [ '755', '644' ]
55 silly gunzTarPerm extractEntry package.json
56 silly gunzTarPerm extractEntry .npmignore
57 silly gunzTarPerm extractEntry README.md
58 silly gunzTarPerm extractEntry index.js
59 silly gunzTarPerm extractEntry binding.gyp
60 silly gunzTarPerm extractEntry get-hidapi.sh
61 silly gunzTarPerm extractEntry install.sh
62 silly gunzTarPerm extractEntry src/.npmignore
63 silly gunzTarPerm extractEntry src/buzzers.js
64 silly gunzTarPerm extractEntry src/powermate.js
65 silly gunzTarPerm extractEntry src/show-devices.js
66 silly gunzTarPerm extractEntry src/test-buzzers.js
67 silly gunzTarPerm extractEntry src/test-powermate.js
68 silly gunzTarPerm extractEntry src/test-ps3.js
69 silly gunzTarPerm extractEntry src/HID.cc
70 silly gunzTarPerm extractEntry src/wscript
71 verbose write writing to /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid/package.json
72 info preinstall node-hid@0.3.2
73 verbose unsafe-perm in lifecycle true
74 verbose readDependencies loading dependencies from /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid/package.json
75 verbose readDependencies loading dependencies from /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid/package.json
76 silly install resolved []
77 verbose about to build /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid
78 info build /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid
79 info linkStuff node-hid@0.3.2
80 silly linkStuff node-hid@0.3.2 has /Users/eeksnider/Desktop/hobby/trojanv2/node_modules as its parent node_modules
81 verbose linkBins node-hid@0.3.2
82 verbose linkMans node-hid@0.3.2
83 verbose rebuildBundles node-hid@0.3.2
84 info install node-hid@0.3.2
85 verbose unsafe-perm in lifecycle true
86 info node-hid@0.3.2 Failed to exec install script
87 verbose unlock done using /Users/eeksnider/.npm/_locks/node-hid-508b441f17e83de6.lock for /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid
88 verbose stack Error: node-hid@0.3.2 install: `sh install.sh`
88 verbose stack Exit status 1
88 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
88 verbose stack     at EventEmitter.emit (events.js:110:17)
88 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
88 verbose stack     at ChildProcess.emit (events.js:110:17)
88 verbose stack     at maybeClose (child_process.js:1015:16)
88 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
89 verbose pkgid node-hid@0.3.2
90 verbose cwd /Users/eeksnider/Desktop/hobby/trojanv2
91 error Darwin 14.0.0
92 error argv "node" "/usr/local/bin/npm" "install" "node-hid"
93 error node v0.12.3
94 error npm  v2.9.1
95 error code ELIFECYCLE
96 error node-hid@0.3.2 install: `sh install.sh`
96 error Exit status 1
97 error Failed at the node-hid@0.3.2 install script 'sh install.sh'.
97 error This is most likely a problem with the node-hid package,
97 error not with npm itself.
97 error Tell the author that this fails on your system:
97 error     sh install.sh
97 error You can get their info via:
97 error     npm owner ls node-hid
97 error There is likely additional logging output above.
98 verbose exit [ 1, true ]
99 verbose unbuild node_modules/node-hid
100 info preuninstall node-hid@0.3.2
101 info uninstall node-hid@0.3.2
102 verbose unbuild rmStuff node-hid@0.3.2 from /Users/eeksnider/Desktop/hobby/trojanv2/node_modules
103 info postuninstall node-hid@0.3.2
104 silly gentlyRm /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid is being purged from base /Users/eeksnider/Desktop/hobby/trojanv2
105 verbose gentlyRm don't care about contents; nuking /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid
106 silly vacuum-fs purging /Users/eeksnider/Desktop/hobby/trojanv2/node_modules/node-hid
107 silly vacuum-fs quitting because other entries in /Users/eeksnider/Desktop/hobby/trojanv2/node_modules

**Comment by robrichard** [comment]
The underlying issue is node-hid not compiling in node 0.12 (https://github.com/node-hid/node-hid/issues/90)

I opened a #5 to bump the node-hid dependency which fixes this.

**Comment by magicpat** [comment]
Would be cool if this dependency bump would be merged, since the node-hid 0.4 dependency uses the nan-layer for > 0.12 & < 0.10 compatibilty... or is there an issue preventing a merge?

**Comment by emilyrose** [comment]
thanks for the report and subsequent discussion, everyone! sorry I missed this for so long.

**Comment by emilyrose** [comment]
Fixed in v2.0.1 (https://github.com/emilyrose/hidstream/commit/af49ef26902f6d3c5791752001ee7eca2db49634)
