### ISSUE TITLE
parser.js line 260 has some problem 

### ISSUE THREAD

**Issue by iamblue** [emilyrose/hidstream#6]
I found some problem in line 260:
https://github.com/emilyrose/hidstream/blob/master/lib/parser.js#L260

data = data.toJSON(); => this `data` is a object, so data.shift() cannot work.

data = data.toJSON().data; will solve this problem ;) ~

**Comment by doleraj** [comment]
+1 this issue.

**Comment by emilyrose** [comment]
@doleraj thanks for bumping this! 😸 

I'll fix this right up.

**Comment by emilyrose** [comment]
I've merged the PR from @iamblue, so closing this now! Thanks for the PR & bump! 😄

**Comment by doleraj** [comment]
Thanks for the fix!
